"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RoleRegistry__factory = exports.BoatPassport__factory = exports.BoatEvents__factory = exports.BoatCertificate__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var BoatCertificate__factory_1 = require("./BoatCertificate__factory");
Object.defineProperty(exports, "BoatCertificate__factory", { enumerable: true, get: function () { return BoatCertificate__factory_1.BoatCertificate__factory; } });
var BoatEvents__factory_1 = require("./BoatEvents__factory");
Object.defineProperty(exports, "BoatEvents__factory", { enumerable: true, get: function () { return BoatEvents__factory_1.BoatEvents__factory; } });
var BoatPassport__factory_1 = require("./BoatPassport__factory");
Object.defineProperty(exports, "BoatPassport__factory", { enumerable: true, get: function () { return BoatPassport__factory_1.BoatPassport__factory; } });
var RoleRegistry__factory_1 = require("./RoleRegistry__factory");
Object.defineProperty(exports, "RoleRegistry__factory", { enumerable: true, get: function () { return RoleRegistry__factory_1.RoleRegistry__factory; } });
