/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BoatCertificate } from "./BoatCertificate";
export type { BoatEvents } from "./BoatEvents";
export type { BoatPassport } from "./BoatPassport";
export type { RoleRegistry } from "./RoleRegistry";
