/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BoatEvents__factory } from "./BoatEvents__factory";
export { BoatPassport__factory } from "./BoatPassport__factory";
export { RoleRegistry__factory } from "./RoleRegistry__factory";
